### ISSUE TITLE
Requesting Python Wheel File

### ISSUE THREAD

**Issue by rrenode** [MagicStack/httptools#19]
Simply requesting the ability to download and install through the whl file

**Comment by adontz** [comment]
Agree, this is crucial for Windows deployments.

**Comment by ramnes** [comment]
Also important for anything running inside containers, if you want to keep your images small and not embed a compiler. The temporary solution is to do some Docker multi-stage magic, but that's boring.

**Comment by elprans** [comment]
Done.
