### ISSUE TITLE
Failed building wheel for httptools

### ISSUE THREAD

**Issue by dejanbatanjac** [MagicStack/httptools#33]
Any idea on possible workaround:

After `pip3 install httptools`:
```
Collecting httptools
  Using cached https://files.pythonhosted.org/packages/1b/03/215969db11abe8741e9c266a4cbe803a372bd86dd35fa0084c4df6d4bd00/httptools-0.0.13.tar.gz
Building wheels for collected packages: httptools
  Building wheel for httptools (setup.py) ... error
  Complete output from command /usr/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-ffzualnz/httptools/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-lq_cgux2 --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/httptools
  copying httptools/__init__.py -> build/lib.linux-x86_64-3.6/httptools
  creating build/lib.linux-x86_64-3.6/httptools/parser
  copying httptools/parser/__init__.py -> build/lib.linux-x86_64-3.6/httptools/parser
  copying httptools/parser/errors.py -> build/lib.linux-x86_64-3.6/httptools/parser
  running egg_info
  writing httptools.egg-info/PKG-INFO
  writing dependency_links to httptools.egg-info/dependency_links.txt
  writing top-level names to httptools.egg-info/top_level.txt
  reading manifest file 'httptools.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'httptools.egg-info/SOURCES.txt'
  copying httptools/parser/parser.c -> build/lib.linux-x86_64-3.6/httptools/parser
  running build_ext
  building 'httptools.parser.parser' extension
  creating build/temp.linux-x86_64-3.6
  creating build/temp.linux-x86_64-3.6/httptools
  creating build/temp.linux-x86_64-3.6/httptools/parser
  creating build/temp.linux-x86_64-3.6/vendor
  creating build/temp.linux-x86_64-3.6/vendor/http-parser
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.6m -c httptools/parser/parser.c -o build/temp.linux-x86_64-3.6/httptools/parser/parser.o -O2
  httptools/parser/parser.c:4:20: fatal error: Python.h: No such file or directory
  compilation terminated.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

  ----------------------------------------
  Failed building wheel for httptools
  Running setup.py clean for httptools
Failed to build httptools
Installing collected packages: httptools
  Running setup.py install for httptools ... error
    Complete output from command /usr/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-ffzualnz/httptools/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-xaxh1zu8/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/httptools
    copying httptools/__init__.py -> build/lib.linux-x86_64-3.6/httptools
    creating build/lib.linux-x86_64-3.6/httptools/parser
    copying httptools/parser/__init__.py -> build/lib.linux-x86_64-3.6/httptools/parser
    copying httptools/parser/errors.py -> build/lib.linux-x86_64-3.6/httptools/parser
    running egg_info
    writing httptools.egg-info/PKG-INFO
    writing dependency_links to httptools.egg-info/dependency_links.txt
    writing top-level names to httptools.egg-info/top_level.txt
    reading manifest file 'httptools.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'httptools.egg-info/SOURCES.txt'
    copying httptools/parser/parser.c -> build/lib.linux-x86_64-3.6/httptools/parser
    running build_ext
    building 'httptools.parser.parser' extension
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/httptools
    creating build/temp.linux-x86_64-3.6/httptools/parser
    creating build/temp.linux-x86_64-3.6/vendor
    creating build/temp.linux-x86_64-3.6/vendor/http-parser
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.6m -c httptools/parser/parser.c -o build/temp.linux-x86_64-3.6/httptools/parser/parser.o -O2
    httptools/parser/parser.c:4:20: fatal error: Python.h: No such file or directory
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

    ----------------------------------------
Command "/usr/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-ffzualnz/httptools/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-xaxh1zu8/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-ffzualnz/httptools/

```
Ubuntu 16.04 LTS

**Comment by sethmlarson** [comment]
`sudo apt-get install python3-dev`?

**Comment by dejanbatanjac** [comment]
Returns `python3-dev is already the newest version (3.5.1-3)`.

**Comment by dejanbatanjac** [comment]
Mark this as resolved. `sudo apt install python3.6-dev` did the job. Thanks!!! I had couple Python versions and 3.6 was simlink to `python3`.

**Comment by tadeoos** [comment]
Actually, can you keep it open? I also have an instalation problem but on the MacOS machie:
```
Collecting httptools
  Using cached https://files.pythonhosted.org/packages/1b/03/215969db11abe8741e9c266a4cbe803a372bd86dd35fa0084c4df6d4bd00/httptools-0.0.13.tar.gz
Installing collected packages: httptools
  Running setup.py install for httptools ... error
    Complete output from command /.../bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/zk/k1js8bq52cb410p7sprvq7dr0000gn/T/pip-install-relolqxm/httptools/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/zk/k1js8bq52cb410p7sprvq7dr0000gn/T/pip-record-39_4i6g8/install-record.txt --single-version-externally-managed --compile --install-headers /.../include/site/python3.7/httptools:
    /.../.pyenv/versions/3.7.1/lib/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution option: 'long_description_content_type'
      warnings.warn(msg)
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.14-x86_64-3.7
    creating build/lib.macosx-10.14-x86_64-3.7/httptools
    copying httptools/__init__.py -> build/lib.macosx-10.14-x86_64-3.7/httptools
    creating build/lib.macosx-10.14-x86_64-3.7/httptools/parser
    copying httptools/parser/__init__.py -> build/lib.macosx-10.14-x86_64-3.7/httptools/parser
    copying httptools/parser/errors.py -> build/lib.macosx-10.14-x86_64-3.7/httptools/parser
    running egg_info
    writing httptools.egg-info/PKG-INFO
    writing dependency_links to httptools.egg-info/dependency_links.txt
    writing top-level names to httptools.egg-info/top_level.txt
    reading manifest file 'httptools.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'httptools.egg-info/SOURCES.txt'
    copying httptools/parser/parser.c -> build/lib.macosx-10.14-x86_64-3.7/httptools/parser
    running build_ext
    building 'httptools.parser.parser' extension
    creating build/temp.macosx-10.14-x86_64-3.7
    creating build/temp.macosx-10.14-x86_64-3.7/httptools
    creating build/temp.macosx-10.14-x86_64-3.7/httptools/parser
    creating build/temp.macosx-10.14-x86_64-3.7/vendor
    creating build/temp.macosx-10.14-x86_64-3.7/vendor/http-parser
    clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/.../include -I/.../versions/3.7.1/include/python3.7m -c httptools/parser/parser.c -o build/temp.macosx-10.14-x86_64-3.7/httptools/parser/parser.o -O2
    clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/.../include -I/.../versions/3.7.1/include/python3.7m -c vendor/http-parser/http_parser.c -o build/temp.macosx-10.14-x86_64-3.7/vendor/http-parser/http_parser.o -O2
    clang -bundle -undefined dynamic_lookup -L/usr/local/opt/readline/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/openssl/lib -L/.../.pyenv/versions/3.7.1/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/openssl/lib -L.../.pyenv/versions/3.7.1/lib build/temp.macosx-10.14-x86_64-3.7/httptools/parser/parser.o build/temp.macosx-10.14-x86_64-3.7/vendor/http-parser/http_parser.o -o build/lib.macosx-10.14-x86_64-3.7/httptools/parser/parser.cpython-37m-darwin.so
    ld: malformed file
    /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/lib/libSystem.tbd:4:18: error: unknown enumerated scalar
    platform:        zippered
                     ^~~~~~~~
     file '/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/lib/libSystem.tbd'
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    error: command 'clang' failed with exit status 1
```

I'm on macOS Mojave 10.14.4
with python 3.7.1, but on 3.6.3 I had the same issue.

**Comment by suponji1025** [comment]
conda install -c conda-forge responder ?

**Comment by suponji1025** [comment]
conda install -c conda-forge httptools

**Comment by cs01** [comment]
> sudo apt install python3.6-dev did the job

I had the same error and had to run `python3.7-dev` to fix it. I added a pull request https://github.com/MagicStack/httptools/pull/34.

@tadeoos does anything on here help? https://stackoverflow.com/questions/15931331/how-to-install-the-python-development-headers-on-mac-os-x

**Comment by Proteusiq** [comment]
I have this error both in Windows 10 64bit Python3.7 and WSL Ubuntu 18.04. None of the dev installations worked but conda. Is there a way to install it with pip? What is the timeline for this issue?

**Comment by hnykda** [comment]
I am having the same issue on Archlinux and conda.

**Comment by ml-evs** [comment]
I'm having a different build issue with GCC (4.9/8.3), Arch and conda with python3.6, if you want to check out #36 @hnykda. I'm able to build without issue with clang.

**Comment by benjamenweber** [comment]
@Proteusiq I was having this issue too on a similar environment.  

I don't remember all the changes I made but I know I installed zlib, libffi, and built 3.7.4 from source and I'm not having issues building httptools anymore.

Something about doing that fixed the issue but I'm not entirely sure what.

**Comment by zero0nee** [comment]
> Actually, can you keep it open? I also have an instalation problem but on the MacOS machie:
> 
> ```
> $ pip install httptools
> Collecting httptools
>   Using cached https://files.pythonhosted.org/packages/1b/03/215969db11abe8741e9c266a4cbe803a372bd86dd35fa0084c4df6d4bd00/httptools-0.0.13.tar.gz
> Installing collected packages: httptools
>   Running setup.py install for httptools ... error
>     Complete output from command /.../bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/zk/k1js8bq52cb410p7sprvq7dr0000gn/T/pip-install-relolqxm/httptools/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/zk/k1js8bq52cb410p7sprvq7dr0000gn/T/pip-record-39_4i6g8/install-record.txt --single-version-externally-managed --compile --install-headers /.../include/site/python3.7/httptools:
>     /.../.pyenv/versions/3.7.1/lib/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution option: 'long_description_content_type'
>       warnings.warn(msg)
>     running install
>     running build
>     running build_py
>     creating build
>     creating build/lib.macosx-10.14-x86_64-3.7
>     creating build/lib.macosx-10.14-x86_64-3.7/httptools
>     copying httptools/__init__.py -> build/lib.macosx-10.14-x86_64-3.7/httptools
>     creating build/lib.macosx-10.14-x86_64-3.7/httptools/parser
>     copying httptools/parser/__init__.py -> build/lib.macosx-10.14-x86_64-3.7/httptools/parser
>     copying httptools/parser/errors.py -> build/lib.macosx-10.14-x86_64-3.7/httptools/parser
>     running egg_info
>     writing httptools.egg-info/PKG-INFO
>     writing dependency_links to httptools.egg-info/dependency_links.txt
>     writing top-level names to httptools.egg-info/top_level.txt
>     reading manifest file 'httptools.egg-info/SOURCES.txt'
>     reading manifest template 'MANIFEST.in'
>     writing manifest file 'httptools.egg-info/SOURCES.txt'
>     copying httptools/parser/parser.c -> build/lib.macosx-10.14-x86_64-3.7/httptools/parser
>     running build_ext
>     building 'httptools.parser.parser' extension
>     creating build/temp.macosx-10.14-x86_64-3.7
>     creating build/temp.macosx-10.14-x86_64-3.7/httptools
>     creating build/temp.macosx-10.14-x86_64-3.7/httptools/parser
>     creating build/temp.macosx-10.14-x86_64-3.7/vendor
>     creating build/temp.macosx-10.14-x86_64-3.7/vendor/http-parser
>     clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/.../include -I/.../versions/3.7.1/include/python3.7m -c httptools/parser/parser.c -o build/temp.macosx-10.14-x86_64-3.7/httptools/parser/parser.o -O2
>     clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/.../include -I/.../versions/3.7.1/include/python3.7m -c vendor/http-parser/http_parser.c -o build/temp.macosx-10.14-x86_64-3.7/vendor/http-parser/http_parser.o -O2
>     clang -bundle -undefined dynamic_lookup -L/usr/local/opt/readline/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/openssl/lib -L/.../.pyenv/versions/3.7.1/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/openssl/lib -L.../.pyenv/versions/3.7.1/lib build/temp.macosx-10.14-x86_64-3.7/httptools/parser/parser.o build/temp.macosx-10.14-x86_64-3.7/vendor/http-parser/http_parser.o -o build/lib.macosx-10.14-x86_64-3.7/httptools/parser/parser.cpython-37m-darwin.so
>     ld: malformed file
>     /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/lib/libSystem.tbd:4:18: error: unknown enumerated scalar
>     platform:        zippered
>                      ^~~~~~~~
>      file '/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/lib/libSystem.tbd'
>     clang: error: linker command failed with exit code 1 (use -v to see invocation)
>     error: command 'clang' failed with exit status 1
> ```
> 
> I'm on macOS Mojave 10.14.4
> with python 3.7.1, but on 3.6.3 I had the same issue.

I'm having the same issue. Did you find a solution?

**Comment by zero0nee** [comment]
Updating to the latest version of Xcode, under "Software Updates" in "System Preferences" solved it for me on Mac.

**Comment by tpinju00** [comment]
@mojimi 

I need help with the same error on Windows10, did you find the solution?

**Comment by DanielLin07** [comment]
> I'm also looking for a solution for Windows 10 that does not include conda

Hey, did u find a solution to solve this issue?

**Comment by SKalt** [comment]
I encountered a similar error in the `python:3.7-slim-stretch` docker image, and I resolved it by switching to `python:3.7-stretch`. I suspect the resolution was that `gcc` was present in `3.7-stretch` and not `3.7-slim-stretch`.


<details>
<summary>the error message I got</summary>

```
 pip install httptools
Collecting httptools
  Downloading https://files.pythonhosted.org/packages/1b/03/215969db11abe8741e9c266a4cbe803a372bd86dd35fa0084c4df6d4bd00/httptools-0.0.13.tar.gz (104kB)
     |████████████████████████████████| 112kB 5.5MB/s 
Building wheels for collected packages: httptools
  Building wheel for httptools (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/local/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-t03x_r1p/httptools/setup.py'"'"'; __file__='"'"'/tmp/pip-install-t03x_r1p/httptools/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-ql_fdimz --python-tag cp37
       cwd: /tmp/pip-install-t03x_r1p/httptools/
  Complete output (28 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.7
  creating build/lib.linux-x86_64-3.7/httptools
  copying httptools/__init__.py -> build/lib.linux-x86_64-3.7/httptools
  creating build/lib.linux-x86_64-3.7/httptools/parser
  copying httptools/parser/errors.py -> build/lib.linux-x86_64-3.7/httptools/parser
  copying httptools/parser/__init__.py -> build/lib.linux-x86_64-3.7/httptools/parser
  running egg_info
  writing httptools.egg-info/PKG-INFO
  writing dependency_links to httptools.egg-info/dependency_links.txt
  writing top-level names to httptools.egg-info/top_level.txt
  reading manifest file 'httptools.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'httptools.egg-info/SOURCES.txt'
  copying httptools/parser/parser.c -> build/lib.linux-x86_64-3.7/httptools/parser
  running build_ext
  building 'httptools.parser.parser' extension
  creating build/temp.linux-x86_64-3.7
  creating build/temp.linux-x86_64-3.7/httptools
  creating build/temp.linux-x86_64-3.7/httptools/parser
  creating build/temp.linux-x86_64-3.7/vendor
  creating build/temp.linux-x86_64-3.7/vendor/http-parser
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/usr/local/include/python3.7m -c httptools/parser/parser.c -o build/temp.linux-x86_64-3.7/httptools/parser/parser.o -O2
  unable to execute 'gcc': No such file or directory
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for httptools
  Running setup.py clean for httptools
Failed to build httptools
Installing collected packages: httptools
  Running setup.py install for httptools ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-t03x_r1p/httptools/setup.py'"'"'; __file__='"'"'/tmp/pip-install-t03x_r1p/httptools/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-6yjs0_zw/install-record.txt --single-version-externally-managed --compile
         cwd: /tmp/pip-install-t03x_r1p/httptools/
    Complete output (28 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.7
    creating build/lib.linux-x86_64-3.7/httptools
    copying httptools/__init__.py -> build/lib.linux-x86_64-3.7/httptools
    creating build/lib.linux-x86_64-3.7/httptools/parser
    copying httptools/parser/errors.py -> build/lib.linux-x86_64-3.7/httptools/parser
    copying httptools/parser/__init__.py -> build/lib.linux-x86_64-3.7/httptools/parser
    running egg_info
    writing httptools.egg-info/PKG-INFO
    writing dependency_links to httptools.egg-info/dependency_links.txt
    writing top-level names to httptools.egg-info/top_level.txt
    reading manifest file 'httptools.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'httptools.egg-info/SOURCES.txt'
    copying httptools/parser/parser.c -> build/lib.linux-x86_64-3.7/httptools/parser
    running build_ext
    building 'httptools.parser.parser' extension
    creating build/temp.linux-x86_64-3.7
    creating build/temp.linux-x86_64-3.7/httptools
    creating build/temp.linux-x86_64-3.7/httptools/parser
    creating build/temp.linux-x86_64-3.7/vendor
    creating build/temp.linux-x86_64-3.7/vendor/http-parser
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/usr/local/include/python3.7m -c httptools/parser/parser.c -o build/temp.linux-x86_64-3.7/httptools/parser/parser.o -O2
    unable to execute 'gcc': No such file or directory
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-t03x_r1p/httptools/setup.py'"'"'; __file__='"'"'/tmp/pip-install-t03x_r1p/httptools/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-6yjs0_zw/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.
```

</details>

**Comment by xgenvn** [comment]
> `sudo apt-get install python3-dev`?

I'm on Ubuntu 19.10 and `apt install python3.7-dev` helping build httptools successfully. Thanks.

**Comment by elprans** [comment]
Wheels are now available.

**Comment by cmacht** [comment]
I ran into a similar issue, where `pip install httptools` works in a python3.8 environment, but not in python3.9. I noticed that pip uses...

* `httptools-0.1.1-cp38-cp38-manylinux1_x86_64.whl` in 3.8
* `httptools-0.1.1.tar.gz` in 3.9

So I'm guessing there are no wheels available for 3.9? I'm on shared hosting so I'm unable to install `python-devel`.

**Comment by niccolomineo** [comment]
Please address this ASAP...

**Comment by cmacht** [comment]
> Please address this ASAP...

@niccolomineo It has been addressed already in #66, check out #59 for details.

**Comment by niccolomineo** [comment]
Hi, thanks for the prompt reply. I realized a package I am using has httptools as a dependency but is still at v 0.1.1.

**Comment by SmadusankaB** [comment]
Same issue on mac os as well. 

`Building wheels for collected packages: httptools
  Building wheel for httptools (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [34 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.macosx-13-x86_64-cpython-311
      creating build/lib.macosx-13-x86_64-cpython-311/httptools
      copying httptools/_version.py -> build/lib.macosx-13-x86_64-cpython-311/httptools
      copying httptools/__init__.py -> build/lib.macosx-13-x86_64-cpython-311/httptools
      creating build/lib.macosx-13-x86_64-cpython-311/httptools/parser
      copying httptools/parser/__init__.py -> build/lib.macosx-13-x86_64-cpython-311/httptools/parser
      copying httptools/parser/errors.py -> build/lib.macosx-13-x86_64-cpython-311/httptools/parser
      running egg_info
      writing httptools.egg-info/PKG-INFO
      writing dependency_links to httptools.egg-info/dependency_links.txt
      writing requirements to httptools.egg-info/requires.txt
      writing top-level names to httptools.egg-info/top_level.txt
      reading manifest file 'httptools.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      adding license file 'LICENSE'
      writing manifest file 'httptools.egg-info/SOURCES.txt'
      copying httptools/parser/parser.c -> build/lib.macosx-13-x86_64-cpython-311/httptools/parser
      running build_ext
      building 'httptools.parser.parser' extension
      creating build/temp.macosx-13-x86_64-cpython-311
      creating build/temp.macosx-13-x86_64-cpython-311/httptools
      creating build/temp.macosx-13-x86_64-cpython-311/httptools/parser
      creating build/temp.macosx-13-x86_64-cpython-311/vendor
      creating build/temp.macosx-13-x86_64-cpython-311/vendor/http-parser
      clang -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/usr/local/opt/python@3.11/Frameworks/Python.framework/Versions/3.11/include/python3.11 -I/private/var/folders/_n/6hwp_mtj08b73s00rrj3b1900000gn/T/pip-install-rcxx3alc/httptools_d3dc7b5f527843ce8a16828690db3996/vendor/http-parser -c httptools/parser/parser.c -o build/temp.macosx-13-x86_64-cpython-311/httptools/parser/parser.o -O2
      httptools/parser/parser.c:212:12: fatal error: 'longintrepr.h' file not found
        #include "longintrepr.h"
                 ^~~~~~~~~~~~~~~
      1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for httptools
  Running setup.py clean for httptools
Failed to build httptools`

**Comment by Nemadede** [comment]
Hi, please I have this issue  in Python 3.12 on MacOs, any solutions

`Building wheels for collected packages: httptools
  Building wheel for httptools (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [32 lines of output]
      /Users/nemadede/Documents/Projects/data-panel-tool/backend/.venv/lib/python3.12/site-packages/setuptools/_distutils/dist.py:261: UserWarning: Unknown distribution option: 'test_suite'
        warnings.warn(msg)
      running bdist_wheel
      running build
      running build_py
      creating build/lib.macosx-10.13-universal2-cpython-312/httptools
      copying httptools/_version.py -> build/lib.macosx-10.13-universal2-cpython-312/httptools
      copying httptools/__init__.py -> build/lib.macosx-10.13-universal2-cpython-312/httptools
      creating build/lib.macosx-10.13-universal2-cpython-312/httptools/parser
      copying httptools/parser/__init__.py -> build/lib.macosx-10.13-universal2-cpython-312/httptools/parser
      copying httptools/parser/errors.py -> build/lib.macosx-10.13-universal2-cpython-312/httptools/parser
      running egg_info
      writing httptools.egg-info/PKG-INFO
      writing dependency_links to httptools.egg-info/dependency_links.txt
      writing requirements to httptools.egg-info/requires.txt
      writing top-level names to httptools.egg-info/top_level.txt
      reading manifest file 'httptools.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      adding license file 'LICENSE'
      writing manifest file 'httptools.egg-info/SOURCES.txt'
      copying httptools/parser/parser.c -> build/lib.macosx-10.13-universal2-cpython-312/httptools/parser
      copying httptools/parser/url_parser.c -> build/lib.macosx-10.13-universal2-cpython-312/httptools/parser
      running build_ext
      building 'httptools.parser.parser' extension
      creating build/temp.macosx-10.13-universal2-cpython-312/httptools/parser
      creating build/temp.macosx-10.13-universal2-cpython-312/vendor/llhttp/src
      clang -fno-strict-overflow -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -O3 -Wall -arch arm64 -arch x86_64 -g -I/private/var/folders/gh/kx9yghwj0tv3v902jy8cm2n40000gn/T/pip-install-pwn9o69g/httptools_36a5bebfdd8f4e3fbcd4fa68cd1dda0a/vendor/llhttp/include -I/private/var/folders/gh/kx9yghwj0tv3v902jy8cm2n40000gn/T/pip-install-pwn9o69g/httptools_36a5bebfdd8f4e3fbcd4fa68cd1dda0a/vendor/llhttp/src -I/Users/nemadede/Documents/Projects/data-panel-tool/backend/.venv/include -I/Library/Frameworks/Python.framework/Versions/3.12/include/python3.12 -c httptools/parser/parser.c -o build/temp.macosx-10.13-universal2-cpython-312/httptools/parser/parser.o -O2
      httptools/parser/parser.c:212:12: fatal error: 'longintrepr.h' file not found
        212 |   #include "longintrepr.h"
            |            ^~~~~~~~~~~~~~~
      1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for httptools
  Running setup.py clean for httptools
Failed to build httptools
ERROR: Could not build wheels for httptools, which is required to install pyproject.toml-based projects`

**Comment by gnusupport** [comment]
I have problem with this too. But 
$ pip install httptools

works well, but when I do

$ pip install vllm
 
I get this:
```text
Using cached pydantic-2.10.5-py3-none-any.whl (431 kB)
Using cached starlette-0.41.3-py3-none-any.whl (73 kB)
Using cached watchgod-0.8.2-py3-none-any.whl (12 kB)
Building wheels for collected packages: httptools
  Building wheel for httptools (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [32 lines of output]
      /home/data1/protected/TTS/lib/python3.11/site-packages/setuptools/_distutils/dist.py:270: UserWarning: Unknown distribution option: 'test_suite'
        warnings.warn(msg)
      running bdist_wheel
      running build
      running build_py
      creating build/lib.linux-x86_64-cpython-311/httptools
      copying httptools/_version.py -> build/lib.linux-x86_64-cpython-311/httptools
      copying httptools/__init__.py -> build/lib.linux-x86_64-cpython-311/httptools
      creating build/lib.linux-x86_64-cpython-311/httptools/parser
      copying httptools/parser/errors.py -> build/lib.linux-x86_64-cpython-311/httptools/parser
      copying httptools/parser/__init__.py -> build/lib.linux-x86_64-cpython-311/httptools/parser
      running egg_info
      writing httptools.egg-info/PKG-INFO
      writing dependency_links to httptools.egg-info/dependency_links.txt
      writing requirements to httptools.egg-info/requires.txt
      writing top-level names to httptools.egg-info/top_level.txt
      reading manifest file 'httptools.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      adding license file 'LICENSE'
      writing manifest file 'httptools.egg-info/SOURCES.txt'
      copying httptools/parser/parser.c -> build/lib.linux-x86_64-cpython-311/httptools/parser
      copying httptools/parser/url_parser.c -> build/lib.linux-x86_64-cpython-311/httptools/parser
      running build_ext
      building 'httptools.parser.parser' extension
      creating build/temp.linux-x86_64-cpython-311/httptools/parser
      creating build/temp.linux-x86_64-cpython-311/vendor/llhttp/src
      x86_64-linux-gnu-gcc -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -I/usr/include/python3.11 -fPIC -I/home/data1/protected/tmp/pip-install-rgwogxkm/httptools_56bae22d6e9647449980faa34050bca5/vendor/llhttp/include -I/home/data1/protected/tmp/pip-install-rgwogxkm/httptools_56bae22d6e9647449980faa34050bca5/vendor/llhttp/src -I/home/data1/protected/TTS/include -I/usr/include/python3.11 -c httptools/parser/parser.c -o build/temp.linux-x86_64-cpython-311/httptools/parser/parser.o -O2
      httptools/parser/parser.c:214:12: fatal error: longintrepr.h: No such file or directory
        214 |   #include "longintrepr.h"
            |            ^~~~~~~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for httptools
  Running setup.py clean for httptools
Failed to build httptools
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (httptools)
(TTS) ~/Programming/git/httptools
```
