### ISSUE TITLE
remove development stage warning?

### ISSUE THREAD

**Issue by samuelcolvin** [MagicStack/httptools#38]
The readme and pypi page starts with the statement:

> It's still in a very early development stage, expect APIs to break.

However the package has the "Development Status :: 5 - Production/Stable" classifier, in addition httptools seems to be used by servers/components like uvicorn which appear to be production ready.

Is it reasonable to assume that httptools is production ready? If so perhaps worth removing that statement?

**Comment by 1st1** [comment]
Yeah! Please make a PR :)
