### ISSUE TITLE
error: Microsoft Visual C++ 14.0 is required.

### ISSUE THREAD

**Issue by Gesujian** [MagicStack/httptools#42]
this happened when I try to install httptools, one error shows up :
Microsoft Visual C++ 14.0 is required.
But I can not find where to download and install it.
I need help.

---------------------------------
httptools-master>python setup.py install
running install
running bdist_egg
running egg_info
creating httptools.egg-info
writing httptools.egg-info\PKG-INFO
writing dependency_links to httptools.egg-info\dependency_links.txt
writing top-level names to httptools.egg-info\top_level.txt
writing manifest file 'httptools.egg-info\SOURCES.txt'
reading manifest file 'httptools.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*.c' under directory 'vendor'
warning: no files found matching '*.h' under directory 'vendor'
warning: no files found matching 'LICENSE*' under directory 'vendor'
warning: no files found matching 'README*' under directory 'vendor'
writing manifest file 'httptools.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
creating build
creating build\lib.win-amd64-3.7
creating build\lib.win-amd64-3.7\httptools
copying httptools\__init__.py -> build\lib.win-amd64-3.7\httptools
creating build\lib.win-amd64-3.7\httptools\parser
copying httptools\parser\errors.py -> build\lib.win-amd64-3.7\httptools\parser
copying httptools\parser\__init__.py -> build\lib.win-amd64-3.7\httptools\parser
running build_ext
building 'httptools.parser.parser' extension
error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/

----------------------------------------------------------------------------

**Comment by elprans** [comment]
Binary wheels are now available for Windows.
