### ISSUE TITLE
httptools.parse_url incorrect parsing Long URL (> 65535 symbols)

### ISSUE THREAD

**Issue by MaksymSkorupskyi** [MagicStack/httptools#43]
We have issues when passing really long URL through Sanic.  It uses httptools.parse_url for parsing URL in Request object. 
It seems that problem is in C++ integer limitations (values from 0 to 65535 (2**16-1)). 
So, If URL is longer 65535 symbols - it will be trimmed.
https://github.com/MagicStack/httptools/blob/master/httptools/parser/parser.pyx#L406

Is it possible to implement bigint instead of int variable in httptools.parse_url or smth like that for such cases? :)

Thanks

**Comment by elprans** [comment]
This is an upstream issue: https://github.com/nodejs/http-parser/issues/481
