### ISSUE TITLE
API change from 0.0.13->0.1.1

### ISSUE THREAD

**Issue by alippai** [MagicStack/httptools#52]
The httptools 1.0.0 release notes say that there should be no breaking change, but upgrading httptools from version 0.0.13 breaks uvicorn tests:

PR: https://github.com/encode/uvicorn/pull/569
Test: https://travis-ci.org/encode/uvicorn/jobs/647886597

**Comment by elprans** [comment]
You should *NOT* import anything from `httptools.parser` directly (that is private API).  The only public API is whatever is available under `httptools` directly, including the exception classes.

**Comment by elprans** [comment]
#53 restores the behavior of 0.0.13, but please fix your code to not import anything from httptools submodules, we will make them private in a future release.
