### ISSUE TITLE
provide wheel for python3.9

### ISSUE THREAD

**Issue by dvzrv** [MagicStack/httptools#59]
Would it be possible to add wheels for python3.9 with a new patch release? :)
Currently it is only possible to compile the package on the fly in a virtualized environment on python3.9.

**Comment by asfaltboy** [comment]
@fantix @elprans could/should we port the Github Actions CI build script from [MagicStack/uvloop](https://github.com/MagicStack/uvloop) into httptools to support 3.9? Or maybe even use [joerick/cibuildwheel](https://github.com/joerick/cibuildwheel)  Or is there another requirement to support 3.9?

**Comment by b0g3r** [comment]
It would be very useful to have wheels for httptools on 3.9. A big part of python's async framework ecosystems (e.g. uvicorn, popular asgi server) depends on httptools. It means, that for installing `uvicorn[standard]` to docker3.9 we need not only python, but also python-dev for building. It's increases the build-time and weight of a resulting image.

I could be wrong, but it looks like all it needed is append 3.9 to the build and test matrix.

**Comment by cmacht** [comment]
+1 because like @b0g3r says, I'm trying to install `uvicorn` for `fastapi` on shared hosting where I cannot fix the missing dependency myself.

**Comment by pauloxnet** [comment]
Thanks for your work on this package.

Can you please release a wheel for Python 3.9 ?

**Comment by pauloxnet** [comment]
@fantix thanks for the `0.2.0` release.

Unfortunately the original request of this issue was a wheel package for the `0.1.1` version of `httptools` for `python 3.9` because, as @b0g3r wrote above, `uvicorn[standard]` require `httptools==0.1.*`

After the 0.2.0 release nothing has changed for people that are using `uvicorn` with `python3.9`.

Can you please add a `python3.9` compatible wheel for `httptools==0.1.1` ?

Thanks in advance for your work here :pray:

**Comment by fantix** [comment]
@pauloxnet oh sure thing! I think I could backport the [3.9 fix](https://github.com/MagicStack/httptools/commit/e2d1a464d113418be26e0b2f36945f032c92a017) together with 9340d32, and release `0.1.2`. Sounds like a plan?

**Comment by fantix** [comment]
Fixed in #66, please feel free to let me know if there're more issues.

**Comment by pauloxnet** [comment]
Yes, thanks it worked.

**Comment by cmacht** [comment]
Wonderful! Thanks for acting so fast! :star2:
