### ISSUE TITLE
Git release/tag for 0.2.0 pypi version

### ISSUE THREAD

**Issue by johncarter-phntm** [MagicStack/httptools#69]
Hi, can you add a git tag + github release for the 0.2.0 version, thanks!

https://github.com/MagicStack/httptools/releases

**Comment by elprans** [comment]
Both the tag and the release record are there and are created automatically in our release workflow.  Perhaps you forgot to prepend `v` to the version number?

**Comment by johncarter-phntm** [comment]
Possibly? I think the github release was confusing because I expected to see v0.2.0 as the most recent release, but v0.1.2 was more recent and therefore listed first & maybe I didn't look further. All good.
