### ISSUE TITLE
Error with specific byte string

### ISSUE THREAD

**Issue by Skorpeo** [MagicStack/httptools#88]
Using python3.11 I just got this random error when I run this.  
```
import httptools
b1 = b'\x16\x03\x01\x02\x00\x01\x00\x01\xfc\x03\x03\xd9\xeaa3\xdb\xc8\xd7\x1c\x02\xe2\x17\\#\t\x96@?z\xf7\t\xd7l\xd7\xac\xf5\xbf\x80\x0eWZ\xe5\xe3 3\x1d~\xb1\x8cT+GI+B\x9e\xc1\xca`\xa0\xdfYPY0\x9cs\x1f\x14\xd3Sa\xb8\x12\xf7\xda\x00$\x13\x01\x13\x03\x13\x02\xc0+\xc0/\xcc\xa9\xcc\xa8\xc0,\xc00\xc0\n'
p = httptools.HttpRequestParser(None)
p.feed_data(b1)
```
File httptools/parser/parser.pyx:212, in httptools.parser.parser.HttpParser.feed_data()

HttpParserInvalidMethodError: Invalid method encountered

Any clue why this is happening??

**Comment by aalexren** [comment]
What do the b1 bytes mean? I can't decode them, could you clarify, please?
