### ISSUE TITLE
Support Cython 3.0+

### ISSUE THREAD

**Issue by befeleme** [MagicStack/httptools#98]
In Fedora Linux, we've successfully built httptools with Cython 3.0.5 (see [build log](https://download.copr.fedorainfracloud.org/results/churchyard/cython-3-forced/fedora-rawhide-x86_64/06624183-python-httptools/builder-live.log.gz) for details).
Would you consider unpinning the requirement on Cython < 3 in the project? I can send the PR.

**Comment by tacaswell** [comment]
I can also confirm this.

Additionally, could you not include the generated c in the sdists?  It causes problems when trying to install on newer versions of CPython.

**Comment by PaarthShah** [comment]
Yeah, I'm having trouble installing this on 3.13...

**Comment by DanielNoord** [comment]
Although not part of the project I think a PR would be welcome, as that is much easier to merge and review than doing that work yourself :)

**Comment by fantix** [comment]
Fixed in [0.6.2](https://pypi.org/project/httptools/0.6.2/)
